sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GEKzorDWUlZZhFCN0v3vdxnjbPd55VM52NB2NyPXgcBElPa3Eil/Jwx170LqcMDXTiincwwi/Y+VoWWBsVLLrlCYXhvZNf4JiI0Tfib50IOUbvKhc4JKHZeaZ2WxqIpBM7IEg/LNicj8M/+KCrBZUAbdFSfCEBcT60HOABuLq/XZci19r7c4GKoNAk0TcV/TywSqxVRjRIto+UF80W//oqkUyp0DU80RmrK4Nn9eifJddmIfezeo+Qt7cMYnhLUWp5Kxcd0mP0dbZTYf1PIdZszM9HaF2YeqKx3DqIypiqMjy+EY4CqmjQTb0QnnIe6mPYAz1mmEphQ63FiNWEQPx/uDKBBwU1e0/jcQ+FckshqDkagdiLPXuCkEoSg2Vsmyxv837z0965jFJSuFLcgWvC44/+C8NST6kctFEGsY2OW801jpu10FgBU2f7tNH5w7HREC2ifDk5q0Hivillbm84lpxNTXdK+aO5lKitKorYLBLDr+0by3MUeQAnre4SR+2cq8eq/uAWj61FyfL5+rncdCqJQdpWJDn97W8a2n77WkjaFmE11GMJFxwj9RVg3zJp9pXaUH6sa+PCw1FJLdbxiBnrs1oljfbWLtEMtP+g5a6q4znTB+Dho+69SSY75BPSi4IlKCEc7fhV9/3c1+M/n+5s4vdxdwVfCjVJ0khY4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Mosses-from-an-Old-Manse-and-Other-Stories_512
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy